################### Dutch Navigation ########################
[[main]]
name = "Over Ons"
url = "#about"
weight = 1

[[main]]
name = "Formules"
url = "#services"
weight = 2

[[main]]
name = "Galerij"
url = "#portfolio"
weight = 3

[[main]]
name = "Contact"
url = "#contact"
weight = 4
